/** Short labels for ambient home-page marquee (100 unique AI-in-business ideas). */
export const AI_BUSINESS_USE_CASES: readonly string[] = [
  'Support ticket triage',
  'First-response email drafts',
  'FAQ generation from tickets',
  'Chatbot for after-hours leads',
  'Meeting notes & action items',
  'Sales call summaries',
  'CRM data cleanup',
  'Lead scoring',
  'Outbound sequence personalization',
  'Proposal outline drafts',
  'RFP response drafting',
  'Competitor mention alerts',
  'Price change monitoring',
  'Job description writing',
  'Resume screening assist',
  'Interview question banks',
  'Onboarding checklist bots',
  'Internal policy Q&A',
  'Expense receipt categorization',
  'Invoice anomaly flagging',
  'Cash-flow commentary drafts',
  'Budget vs. actual narratives',
  'Vendor contract clause flags',
  'NDA playbook checks',
  'Regulatory change digests',
  'Safety incident report drafts',
  'Quality inspection image assist',
  'Predictive maintenance signals',
  'Route optimization hints',
  'Warehouse slotting suggestions',
  'Demand forecasting assist',
  'SKU description generation',
  'Return reason clustering',
  'Review sentiment tracking',
  'Social mention triage',
  'Ad copy variants',
  'SEO meta tag suggestions',
  'Blog outline generation',
  'Video script beats',
  'Brand voice consistency check',
  'Translation & localization',
  'Accessibility alt-text drafts',
  'Product doc from release notes',
  'API error explanation pages',
  'Developer onboarding guides',
  'Code review comment nudges',
  'Test case suggestions',
  'Log pattern anomaly alerts',
  'Incident timeline assembly',
  'Runbook step suggestions',
  'Phishing email simulation',
  'Access request summarization',
  'IT ticket routing',
  'Password-reset deflection',
  'Device policy Q&A',
  'Real estate listing copy',
  'Mortgage doc checklist bots',
  'Insurance claim intake assist',
  'Medical coding prep assist',
  'Patient intake form summaries',
  'Clinical trial eligibility screens',
  'Legal hold tracking reminders',
  'Trademark conflict scans',
  'Patent prior-art search assist',
  'Board deck executive summaries',
  'OKR progress narratives',
  '360 feedback synthesis',
  'Training quiz generation',
  'Compliance training scenarios',
  'ESG report narrative drafts',
  'Carbon footprint estimate assist',
  'Supplier ESG questionnaire help',
  'Restaurant menu allergen notes',
  'Hotel guest message replies',
  'Travel itinerary optimization',
  'Event attendee matchmaking',
  'Webinar Q&A sorting',
  'Podcast show notes',
  'Newsletter topic clustering',
  'Customer interview insight tags',
  'NPS comment themes',
  'Churn risk narrative',
  'Upsell moment suggestions',
  'Renewal email personalization',
  'Partner portal Q&A',
  'Dealer inventory descriptions',
  'Franchise ops manual Q&A',
  'Field service dispatch hints',
  'Work order completion summaries',
  'Construction punch-list OCR',
  'Blueprint revision summaries',
  'Permit packet checklists',
  'Solar proposal savings narratives',
  'Fleet fuel anomaly alerts',
  'Driver safety coaching tips',
  'Agriculture yield advisory text',
  'Livestock health log summaries',
  'Fashion trend digest for buyers',
  'Jewelry appraisal narrative assist',
  'Music licensing clearance hints',
];
